[package]
name = "proton"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "55.0.0"
bigdecimal = "0.4.8"
num-bigint = "0.4.6"
num-traits = "0.2.19"
owo-colors = "4.2.0"
polars = { version = "0.47.1", features = ["parquet"]}
schemars = "0.8.22"
